nnn: update fzcd

diff --git a/4scripts/nnn-plugins/fzcd b/4scripts/nnn-plugins/fzcd
--- a/4scripts/nnn-plugins/fzcd
+++ b/4scripts/nnn-plugins/fzcd
@@ -18,70 +18,70 @@
 #          - OR, edit selection in nnn and save as path-list file
 #
 # Shell: POSIX compliant
-# Author: Anna Arad, Arun Prakash Jana
+# Author: Anna Arad, Arun Prakash Jana, KlzXS
 
 IFS="$(printf '\n\r')"
 
+# shellcheck disable=SC1090,SC1091
 . "$(dirname "$0")"/.nnn-plugin-helper
 
 CTX=+
-LIST="$LIST"
+LIST="${LIST:-""}"
 
 if ! type fzf >/dev/null 2>&1; then
-	printf "fzf missing"
-	read -r _
-	exit 1
+    printf "fzf missing"
+    read -r _
+    exit 1
 fi
 
 if [ -n "$1" ] && [ "$(file -b --mime-type "$1")" = 'text/plain' ] && [ -e "$(head -1 "$1")" ]; then
-	LIST="$1"
+    LIST="$1"
 elif ! [ -s "$LIST" ]; then
-	sel=$(fzf)
-	# Show only the file and parent dir
-	# sel=$(fzf --delimiter / --with-nth=-2,-1 --tiebreak=begin --info=hidden)
+    sel=$(fzf)
+    # Show only the file and parent dir
+    # sel=$(fzf --delimiter / --with-nth=-2,-1 --tiebreak=begin --info=hidden)
 
-	LIST=''
+    LIST=''
 fi
 
 if [ -n "$LIST" ]; then
-	if type fd >/dev/null 2>&1; then
-		tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
+    if type fd >/dev/null 2>&1; then
+        tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
 
-		while IFS= read -r path; do
-			if [ -d "$path" ]; then
-				printf "%s\n" "$path" >>"$tmpfile"
-			elif [ -f "$path" ]; then
-				printf "%s\n" "$(dirname "$path")" >>"$tmpfile"
-			fi
-		done <"$LIST"
+        while IFS= read -r path; do
+            if [ -d "$path" ]; then
+                printf "%s\n" "$path" >> "$tmpfile"
+            elif [ -f "$path" ]; then
+                printf "%s\n" "$(dirname "$path")" >> "$tmpfile"
+            fi
+        done < "$LIST"
 
-		sel=$(xargs -d '\n' -a "$tmpfile" fd -H . | fzf --delimiter / --tiebreak=begin --info=hidden)
+        sel=$(xargs -d '\n' < "$tmpfile" fd . | fzf --delimiter / --tiebreak=begin --info=hidden)
 
-		rm "$tmpfile"
-	else
-		printf "fd missing"
-		read -r _
-		exit 1
-	fi
+        rm "$tmpfile"
+    else
+        printf "fd missing"
+        read -r _
+            exit 1
+    fi
 fi
 
 if [ -n "$sel" ]; then
-	if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
-		exit 0
-	fi
+    if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
+        exit 0
+    fi
 
-	# Check if the selected path returned by fzf command is absolute
-	case $sel in
-	/*) nnn_cd "$sel" "$CTX" ;;
-	*)
-		# Remove "./" prefix if it exists
-		sel="${sel#./}"
+    # Check if the selected path returned by fzf command is absolute
+    case $sel in
+    /*) nnn_cd "$sel" "$CTX" ;;
+    *)
+        # Remove "./" prefix if it exists
+        sel="${sel#./}"
 
-		if [ "$PWD" = "/" ]; then
-			nnn_cd "/$sel" "$CTX"
-		else
-			nnn_cd "$PWD/$sel" "$CTX"
-		fi
-		;;
-	esac
+        if [ "$PWD" = "/" ]; then
+            nnn_cd "/$sel" "$CTX"
+        else
+            nnn_cd "$PWD/$sel" "$CTX"
+        fi;;
+    esac
 fi
